fixup review comments.
Signed-off-by: Quentin Casasnovas <quentin.casasnovas@vates.tech>

diff --git a/scripts/git-import-srpm b/scripts/git-import-srpm
--- a/scripts/git-import-srpm
+++ b/scripts/git-import-srpm
@@ -1,7 +1,7 @@
 #!/bin/bash -eu
 #
 # tl;dr:
-# - To import a specific revision revision, provided you're in srpm repo:
+# - To import a specific revision, provided you're in the srpm repo:
 #     git-import-srpm HEAD
 #
 # - To import all revisions (the script will dedupe the branches):
@@ -33,49 +33,26 @@
 
 THIS_SCRIPT="$(readlink -f "$0")"
 
-SRPM_REPO_PATH=${SRPM_REPO_PATH:-$(pwd)}
-
-function product() {
-    if [ -f "${SRPM_REPO_PATH}/SPECS/kernel.spec" ]; then
-	echo -n "linux"
-    elif [ -f "${SRPM_REPO_PATH}/SPECS/xen.spec" ]; then
-	echo -n "xen"
-    elif [ -f "${SRPM_REPO_PATH}/SPECS/qemu.spec" ]; then
-	echo -n "qemu"
-    else
-	exit 1
-    fi
-}
-
-case "$(product)" in
-    linux)
-	CODE_REPO_PATH="${CODE_REPO_PATH:-${SRPM_REPO_PATH}/../linux/}"
-	SPEC_FILE="SPECS/kernel.spec"
-	RELEASE_PREFIX="v"
-	;;
-    xen)
-	CODE_REPO_PATH="${CODE_REPO_PATH:-${SRPM_REPO_PATH}/../xen/}"
-	SPEC_FILE="SPECS/xen.spec"
-	RELEASE_PREFIX="RELEASE-"
-	;;
-    qemu)
-	CODE_REPO_PATH="${CODE_REPO_PATH:-${SRPM_REPO_PATH}/../qemu/}"
-	SPEC_FILE="SPECS/qemu.spec"
-	RELEASE_PREFIX="v"
-	;;
-    *)
-	echo "Unknown package"
-	exit 1
-	;;
-esac
+SRPM_REPO_PATH=${SRPM_REPO_PATH:-${PWD}}
+PRODUCT=$(basename ${SRPM_REPO_PATH}/SPECS/*.spec .spec)
+CODE_REPO_PATH="${CODE_REPO_PATH:-${SRPM_REPO_PATH}/../${PRODUCT}/}"
+SPEC_FILE="SPECS/${PRODUCT}.spec"
+if [ "${PRODUCT}" = "kernel" -o "${PRODUCT}" = "qemu" ]; then
+    RELEASE_PREFIX="v"
+elif [ "${PRODUCT}" = "xen" ]; then
+    RELEASE_PREFIX="RELEASE-"
+else
+    echo "Unknown package: '${PRODUCT}'"
+    exit 1
+fi
 
 function get_build_dir() {
     local worktree="$1"
     local revision="$2"
 
     git -C ${worktree} show "${revision}:${SPEC_FILE}" | \
-	rpmspec --query --define "_topdir ${worktree}" --qf '%{name}-%{version}\n' /dev/stdin 2>> "${COMMAND_LOGS}" | \
-	head -n 1
+        rpmspec --query --define "_topdir ${worktree}" --qf '%{name}-%{version}\n' /dev/stdin 2>> "${COMMAND_LOGS}" | \
+        head -n 1
 }
 
 function get_base_version() {
@@ -83,7 +60,7 @@ function get_base_version() {
     local revision="$2"
 
     if [ "$(git -C ${worktree} ls-tree --name-only ${revision} SPECS/)" != "${SPEC_FILE}" ]; then
-	return
+        return
     fi
 
     git -C ${worktree} show "${revision}:${SPEC_FILE}" | rpmspec -P /dev/stdin 2>> "${COMMAND_LOGS}" | awk "/^Version:/{print \"${RELEASE_PREFIX}\" \$NF}"
@@ -94,7 +71,7 @@ function get_release() {
     local revision="$2"
 
     if [ "$(git -C ${worktree} ls-tree --name-only ${revision} SPECS/)" != "${SPEC_FILE}" ]; then
-	return
+        return
     fi
 
     git -C ${worktree} show "${revision}:${SPEC_FILE}" | rpmspec -P /dev/stdin 2>> "${COMMAND_LOGS}" | awk '/^Release:/{print $NF}'
@@ -112,12 +89,12 @@ function get_vendor() {
     local revision="$2"
 
     if [ "$(git -C ${worktree} ls-tree --name-only ${revision} SPECS/)" != "${SPEC_FILE}" ]; then
-	return
+        return
     fi
 
     git -C ${worktree} show "${revision}:${SPEC_FILE}" | grep -q -e XCP-ng -e xcp \
-	&& echo "xcpng" \
-	|| echo "xenserver"
+        && echo "xcpng" \
+        || echo "xenserver"
 }
 
 function get_branch_name() {
@@ -133,9 +110,9 @@ function get_branch_name() {
     full_version="$(get_full_version "${base_version}" "${release}")"
 
     if [ -z "${vendor}" -o -z "{full_version}" ]; then
-	echo "unknown_branch_name_for_rev_${revision}"
+        echo "unknown_branch_name_for_rev_${revision}"
     else
-	echo "$(product)/${vendor}-${full_version}/base"
+        echo "${PRODUCT}/${vendor}-${full_version}/base"
     fi
 
 }
@@ -149,10 +126,10 @@ function init_worktrees() {
 
     # Upstream stable base
     base_version=$(get_base_version "${srpm_repo_worktree}" HEAD)
-    if [ "$(product)" == "xen" ]; then
-	if [ "${base_version}" = RELEASE-4.13.0 ]; then
-	    base_version=85e1424de2dda
-	fi
+    if [ "${PRODUCT}" == "xen" ]; then
+        if [ "${base_version}" = RELEASE-4.13.0 ]; then
+            base_version=85e1424de2dda
+        fi
     fi
 
     BRANCH_NAME="$(get_branch_name "${srpm_repo_worktree}" HEAD)"
@@ -160,14 +137,14 @@ function init_worktrees() {
     echo "[+] Constructing ${BRANCH_NAME} from rev ${srpm_repo_revision}"
 
     git -C ${CODE_REPO_PATH} show-ref --verify --quiet refs/heads/${BRANCH_NAME} && {
-     	echo "[-] branch ${BRANCH_NAME} already exists"
-	exit 1
+        echo "[-] branch ${BRANCH_NAME} already exists"
+        exit 1
     } || :
 
 
     git -C "${CODE_REPO_PATH}" rev-parse ${base_version} 2> /dev/null > /dev/null || {
-	echo "- ${BRANCH_NAME}: ${base_version} cannot be found, have you fetched"
-	exit 1
+        echo "- ${BRANCH_NAME}: ${base_version} cannot be found, have you fetched"
+        exit 1
     }
 
     git -C ${CODE_REPO_PATH} worktree add -B "${BRANCH_NAME}-partial" "${code_repo_worktree}" "${base_version}" >> "${COMMAND_LOGS}" 2>> "${COMMAND_LOGS}"
@@ -239,7 +216,7 @@ function apply_patch() {
     # and causes history to diverge early in similar branches.  Simply do
     # not apply it.
     if [ "$(basename ${p})" = "changeset-info.patch" ] ; then
-	return 0
+        return 0
     fi
 
     export_author
@@ -249,43 +226,43 @@ function apply_patch() {
     local git_dir=$(git rev-parse --git-dir)
     git am -3 < "${patch}" || (
 
-	local unmerged_files="$(git status -s | grep '^UU')"
-	local changes="$(git status -s)"
+        local unmerged_files="$(git status -s | grep '^UU')"
+        local changes="$(git status -s)"
 
-	if [ -n "${unmerged_files}" -o -z "${changes}" ]; then
-	    # The patch didn't apply.  Sometimes git am is a bit more
-	    # peculiar than a patch command, especially if there are index
-	    # information it doesn't have in its tree.  In that case
-	    # fallback to patch.
-	    git reset --hard
-	    patch -p1 --fuzz=2 < "${patch}" || return 1
-	    git add -A
-	    # An error for this git am falls through, likely caused by
-	    # missing author information, so we'll use git commit directly
-	    # below.
-	    git am --continue && return 0 || :
-	fi
-
-	# This one is used when we fallback to plain git commit
-	export GIT_AUTHOR_DATE="1442642982"
-	if [ -s "${git_dir}"/rebase-apply/msg ]; then
-
-	    load_author_and_title "${patch}" "${git_dir}"
-
-	    if [ "$(basename ${p})" = "qemu-4.2.1-CVE-2023-3354.backport.patch" ]; then
-		# Patch is malformed
-		sed -i '1i\io: remove io watch if TLS channel is closed during handshake\n' "${git_dir}"/rebase-apply/msg
-		export GIT_AUTHOR_NAME="Daniel P. Berrangé"
-		export GIT_AUTHOR_EMAIL="<berrange@redhat.com>"
-	    fi
-
-	    # There was a commit description, so try and use it
-	    git commit -F "${git_dir}"/rebase-apply/msg && git am --skip
-	else
-	    # No commit description, use the patch path
-	    git commit -m "$(basename ${p})" && git am --skip
+        if [ -n "${unmerged_files}" -o -z "${changes}" ]; then
+            # The patch didn't apply.  Sometimes git am is a bit more
+            # peculiar than a patch command, especially if there are index
+            # information it doesn't have in its tree.  In that case
+            # fallback to patch.
+            git reset --hard
+            patch -p1 --fuzz=2 < "${patch}" || return 1
+            git add -A
+            # An error for this git am falls through, likely caused by
+            # missing author information, so we'll use git commit directly
+            # below.
+            git am --continue && return 0 || :
         fi
-	return $?
+
+        # This one is used when we fallback to plain git commit
+        export GIT_AUTHOR_DATE="1442642982"
+        if [ -s "${git_dir}"/rebase-apply/msg ]; then
+
+            load_author_and_title "${patch}" "${git_dir}"
+
+            if [ "$(basename ${p})" = "qemu-4.2.1-CVE-2023-3354.backport.patch" ]; then
+                # Patch is malformed
+                sed -i '1i\io: remove io watch if TLS channel is closed during handshake\n' "${git_dir}"/rebase-apply/msg
+                export GIT_AUTHOR_NAME="Daniel P. Berrangé"
+                export GIT_AUTHOR_EMAIL="<berrange@redhat.com>"
+            fi
+
+            # There was a commit description, so try and use it
+            git commit -F "${git_dir}"/rebase-apply/msg && git am --skip
+        else
+            # No commit description, use the patch path
+            git commit -m "$(basename ${p})" && git am --skip
+        fi
+        return $?
 
     ) || return 1
     return 0
@@ -321,22 +298,22 @@ function import_all_branches() {
     cd ${SRPM_REPO_PATH}
 
     for revision in $(git rev-list --topo-order HEAD); do
-	local branch_name="$(get_branch_name $(pwd) ${revision} 2>> "${COMMAND_LOGS}")"
-	if [ -z "${revs_for_version[${branch_name}]:-}" ]; then
-	    revs_for_version[${branch_name}]="${revision}"
-	fi
+        local branch_name="$(get_branch_name ${PWD} ${revision} 2>> "${COMMAND_LOGS}")"
+        if [ -z "${revs_for_version[${branch_name}]:-}" ]; then
+            revs_for_version[${branch_name}]="${revision}"
+        fi
     done
 
     for b in ${!revs_for_version[@]}; do
-	local revision="${revs_for_version[${b}]}"
-	case ${b} in
-	    unknown_branch_name*)
-		echo "Could not infer a branch name for revision: ${revision}" 1&>2
-		;;
-	    *)
-		echo ${revs_for_version[${b}]}
-		;;
-	esac
+        local revision="${revs_for_version[${b}]}"
+        case ${b} in
+            unknown_branch_name*)
+                echo "Could not infer a branch name for revision: ${revision}" 1&>2
+                ;;
+            *)
+                echo ${revs_for_version[${b}]}
+                ;;
+        esac
     done | (SRPM_REPO_PATH="${SRPM_REPO_PATH}" CODE_REPO_PATH="${CODE_REPO_PATH}" xargs -n 1 -P $(nproc) ${THIS_SCRIPT})
 }
 
@@ -346,7 +323,7 @@ test -f ${COMMAND_LOGS} && rm ${COMMAND_LOGS} || :
 
 if [ "$1" = "--all" ]; then
     import_all_branches
-    exit $$
+    exit 0
 fi
 
 SRPM_REPO_REVISION=$1
@@ -373,25 +350,25 @@ apply_spec_quirks
 # built on older version of rpmbuild would apply it with --fuzz=2, so make
 # sure to use --fuzz=2 here.
 rpmbuild --nodeps \
-	 --define "_buildshell /bin/bash" \
-	 --define "_topdir ${SRPM_REPO_WORKTREE}" \
-	 --define "_default_patch_fuzz 2" \
-	 --eval "%{_default_patch_fuzz}" \
-	 -bp ${SRPM_REPO_WORKTREE}/${SPEC_FILE} 2>> ${COMMAND_LOGS} >> ${COMMAND_LOGS} &
+         --define "_buildshell /bin/bash" \
+         --define "_topdir ${SRPM_REPO_WORKTREE}" \
+         --define "_default_patch_fuzz 2" \
+         --eval "%{_default_patch_fuzz}" \
+         -bp ${SRPM_REPO_WORKTREE}/${SPEC_FILE} 2>> ${COMMAND_LOGS} >> ${COMMAND_LOGS} &
 RPMBUILD_PID=$!
 
 cd ${SRPM_REPO_WORKTREE}
 
 git show "HEAD:${SPEC_FILE}" | while IFS= read -r l; do
     case "${l}" in
-	Patch*)
-	    p="${l#* }"
-	    apply_patch "${CODE_REPO_WORKTREE}" "${SRPM_REPO_WORKTREE}/SOURCES/${p}" >> "${COMMAND_LOGS}" 2>> "${COMMAND_LOGS}" || {
-		echo "[-] [apply_patch] Failed reconstructing ${BRANCH_NAME} for ${SRPM_REPO_REVISION}, check ${COMMAND_LOGS}"
-		exit 1
+        Patch*)
+            p="${l#* }"
+            apply_patch "${CODE_REPO_WORKTREE}" "${SRPM_REPO_WORKTREE}/SOURCES/${p}" >> "${COMMAND_LOGS}" 2>> "${COMMAND_LOGS}" || {
+                echo "[-] [apply_patch] Failed reconstructing ${BRANCH_NAME} for ${SRPM_REPO_REVISION}, check ${COMMAND_LOGS}"
+                exit 1
 
-	    }
-	    ;;
+            }
+            ;;
     esac
 done
 
